const api = process.env.VUE_APP_API_URL_BASE
const social = process.env.VUE_APP_SOCIAL
export default {
  VOCATIONS: () => `https://sim.idrd.gov.co/base-ldap/public/api/vocations`,
  VIGILANCE: () => `https://sim.idrd.gov.co/base-ldap/public/api/vigilance`,
  CONCERNS: () => `https://sim.idrd.gov.co/base-ldap/public/api/concerns`,
  STAGE_TYPES: () => `https://sim.idrd.gov.co/base-ldap/public/api/stage-types`,
  SCALE: () => `https://sim.idrd.gov.co/base-ldap/public/api/scales`,
  STATUS: () => `https://sim.idrd.gov.co/base-ldap/public/api/statuses`,
  UPZ_TYPES: () => `https://sim.idrd.gov.co/base-ldap/public/api/upz-types`,
  CERTIFICATE_STATUS: () => `https://sim.idrd.gov.co/base-ldap/public/api/certificate-status`,
  TYPE_ZONES: () => `https://sim.idrd.gov.co/base-ldap/public/api/type-zones`,
  ENCLOSURES: () => `https://sim.idrd.gov.co/base-ldap/public/api/enclosures`,
  LOCALITIES: () => `https://sim.idrd.gov.co/base-ldap/public/api/localities`,
  UPZ: (location) => `https://sim.idrd.gov.co/base-ldap/public/api/localities/${location}/upz`,
  UPZALL: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/get-upzs`,
  NEIGHBORHOODS: (location, upz) =>
    `https://sim.idrd.gov.co/base-ldap/public/api/localities/${location}/upz/${upz}/neighborhoods`,
  NEIGHBORHOODALL: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/get-neighborhood`,
  PARKS: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks`,
  PARKS_AUDIT: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/audits`,
  OWNED: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/owned`,
  DESTROY_OWNED: (userId, parkId) =>
    `https://sim.idrd.gov.co/base-ldap/public/api/parks/owned/${userId}/${parkId}`,
  DESTROY_ALL_OWNED: (userId) => `https://sim.idrd.gov.co/base-ldap/public/api/parks/destroy-all-owned/${userId}`,
  OWNED_KEYS: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/owned-keys`,
  EXCEL: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/excel`,
  RUPI: (id) => `https://sim.idrd.gov.co/base-ldap/public/api/parks/${id}/rupis`,
  ORIGIN: (id) => `https://sim.idrd.gov.co/base-ldap/public/api/parks/${id}/origin`,
  STORIES: (id) => `https://sim.idrd.gov.co/base-ldap/public/api/parks/${id}/stories`,
  EQUIPMENTS: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/equipments`,
  EQUIPMENTS_ENDOWMENTS: (id) => `https://sim.idrd.gov.co/base-ldap/public/api/parks/equipments/${id}/endowments`,
  PARKS_ESRI_CONFIG: () => `https://sim.idrd.gov.co/base-ldap/public/api/esri/config`,
  PARKS_SECTORS: (id) => `https://sim.idrd.gov.co/base-ldap/public/api/parks/${id}/sectors`,
  PARKS_ECONOMIC: (id) => `https://sim.idrd.gov.co/base-ldap/public/api/parks/${id}/economic-use`,
  PARKS_FURNITURE: (id) => `https://sim.idrd.gov.co/base-ldap/public/api/parks/${id}/furnishings`,
  PARKS_EQUIPMENT: (parkId, equipmentId) =>
    `https://sim.idrd.gov.co/base-ldap/public/api/parks/${parkId}/equipment/${equipmentId}`,
  SYNTHETIC: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/synthetic-fields`,
  DIAGRAMS: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/diagrams`,
  PARKS_PERMISSIONS: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/user/permissions`,
  PARKS_ADMIN_PERMISSIONS: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/admin/permissions`,
  PARKS_ADMIN_ROLES: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/admin/roles`,
  PARKS_ADMIN_ROLES_PERMISSION: (roleId, permissionId) =>
    `https://sim.idrd.gov.co/base-ldap/public/api/parks/admin/roles/${roleId}/permissions/${
      !permissionId ? '' : permissionId
    }`,
  PARKS_ADMIN_ENTITIES: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/admin/models`,
  PARKS_ROLES: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/users/roles`,
  PARKS_MENU: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/user/menu`,
  PARKS_USERS: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/users`,
  PARKS_FIND_USERS: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/users/find`,
  PARKS_ROLES_USER: (userId) => `https://sim.idrd.gov.co/base-ldap/public/api/parks/users/roles/${userId}`,
  PARKS_STATS_EXCEL: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/stats/excel`,
  PARKS_STATS_BY_TYPE: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/stats`,
  PARKS_STATS_BY_COUNT: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/stats/count`,
  PARKS_STATS_BY_ENCLOSURE: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/stats/enclosure`,
  PARKS_STATS_BY_LOCALITY: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/stats/localities`,
  PARKS_STATS_BY_CERTIFICATION: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/stats/certified`,
  PARKS_STATS_BY_UPZ: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/stats/upz`,
  PARKS_STATS_BY_ENDOWMENTS: (id) => `https://sim.idrd.gov.co/base-ldap/public/api/parks/stats/endowments/${id}`,
  PARKS_ACTIVITIES: (parkId) => `${social}/api/recreation/${parkId}/calendar`,
  PARKS_ACTIVITIES_SPORTS: () => `https://sim.idrd.gov.co/base-ldap/public/api/citizen-portal/public-schedules`,
  PARKS_IDRD_EVENTS: () => process.env.VUE_APP_EVENTOS_IDRD,
  PARKS_SOCIAL_PROGRAMS: (parkId) =>
    `${social}/api/social-management/${parkId}/history`,
  PARKS_RESERVATIONS: (parkId, endowmentId) =>
    `https://www.idrd.gov.co/SIM/PAGOS_PSE/?idParque=${parkId}&idDotacion=${endowmentId}`,
  PARKS_FEATURES: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/features`,
  PARKS_FEATURES_REMOVE: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/features/remove`,
  PARKS_FEATURES_ADD: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/features/add`,
  PARKS_CATEGORIES_PLAN: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/plans/categories-plans`,
  PARKS_PLAN_ADD: () => `https://sim.idrd.gov.co/base-ldap/public/api/parks/plans/add`,
}

